// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: api/pingpongapi/pingpongapi.proto

package pingpongapi

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PingPongReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *PingPongReq) Reset() {
	*x = PingPongReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pingpongapi_pingpongapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingPongReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPongReq) ProtoMessage() {}

func (x *PingPongReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pingpongapi_pingpongapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPongReq.ProtoReflect.Descriptor instead.
func (*PingPongReq) Descriptor() ([]byte, []int) {
	return file_api_pingpongapi_pingpongapi_proto_rawDescGZIP(), []int{0}
}

func (x *PingPongReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PingPongRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *PingPongRsp) Reset() {
	*x = PingPongRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pingpongapi_pingpongapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingPongRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPongRsp) ProtoMessage() {}

func (x *PingPongRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pingpongapi_pingpongapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPongRsp.ProtoReflect.Descriptor instead.
func (*PingPongRsp) Descriptor() ([]byte, []int) {
	return file_api_pingpongapi_pingpongapi_proto_rawDescGZIP(), []int{1}
}

func (x *PingPongRsp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_api_pingpongapi_pingpongapi_proto protoreflect.FileDescriptor

var file_api_pingpongapi_pingpongapi_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6e, 0x67, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6e, 0x67, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6e, 0x67, 0x61, 0x70, 0x69,
	0x22, 0x21, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x65, 0x78, 0x74, 0x22, 0x21, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x52,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x32, 0x4a, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f,
	0x6e, 0x67, 0x12, 0x3e, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x18,
	0x2e, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6e, 0x67, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x50, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x69, 0x6e, 0x67, 0x70,
	0x6f, 0x6e, 0x67, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x52,
	0x73, 0x70, 0x42, 0x11, 0x5a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x6f,
	0x6e, 0x67, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_pingpongapi_pingpongapi_proto_rawDescOnce sync.Once
	file_api_pingpongapi_pingpongapi_proto_rawDescData = file_api_pingpongapi_pingpongapi_proto_rawDesc
)

func file_api_pingpongapi_pingpongapi_proto_rawDescGZIP() []byte {
	file_api_pingpongapi_pingpongapi_proto_rawDescOnce.Do(func() {
		file_api_pingpongapi_pingpongapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pingpongapi_pingpongapi_proto_rawDescData)
	})
	return file_api_pingpongapi_pingpongapi_proto_rawDescData
}

var file_api_pingpongapi_pingpongapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_pingpongapi_pingpongapi_proto_goTypes = []interface{}{
	(*PingPongReq)(nil), // 0: pingpongapi.PingPongReq
	(*PingPongRsp)(nil), // 1: pingpongapi.PingPongRsp
}
var file_api_pingpongapi_pingpongapi_proto_depIdxs = []int32{
	0, // 0: pingpongapi.PingPong.PingPong:input_type -> pingpongapi.PingPongReq
	1, // 1: pingpongapi.PingPong.PingPong:output_type -> pingpongapi.PingPongRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pingpongapi_pingpongapi_proto_init() }
func file_api_pingpongapi_pingpongapi_proto_init() {
	if File_api_pingpongapi_pingpongapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_pingpongapi_pingpongapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingPongReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pingpongapi_pingpongapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingPongRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pingpongapi_pingpongapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pingpongapi_pingpongapi_proto_goTypes,
		DependencyIndexes: file_api_pingpongapi_pingpongapi_proto_depIdxs,
		MessageInfos:      file_api_pingpongapi_pingpongapi_proto_msgTypes,
	}.Build()
	File_api_pingpongapi_pingpongapi_proto = out.File
	file_api_pingpongapi_pingpongapi_proto_rawDesc = nil
	file_api_pingpongapi_pingpongapi_proto_goTypes = nil
	file_api_pingpongapi_pingpongapi_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PingPongClient is the client API for PingPong service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingPongClient interface {
	PingPong(ctx context.Context, in *PingPongReq, opts ...grpc.CallOption) (*PingPongRsp, error)
}

type pingPongClient struct {
	cc grpc.ClientConnInterface
}

func NewPingPongClient(cc grpc.ClientConnInterface) PingPongClient {
	return &pingPongClient{cc}
}

func (c *pingPongClient) PingPong(ctx context.Context, in *PingPongReq, opts ...grpc.CallOption) (*PingPongRsp, error) {
	out := new(PingPongRsp)
	err := c.cc.Invoke(ctx, "/pingpongapi.PingPong/PingPong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingPongServer is the server API for PingPong service.
type PingPongServer interface {
	PingPong(context.Context, *PingPongReq) (*PingPongRsp, error)
}

// UnimplementedPingPongServer can be embedded to have forward compatible implementations.
type UnimplementedPingPongServer struct {
}

func (*UnimplementedPingPongServer) PingPong(context.Context, *PingPongReq) (*PingPongRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingPong not implemented")
}

func RegisterPingPongServer(s *grpc.Server, srv PingPongServer) {
	s.RegisterService(&_PingPong_serviceDesc, srv)
}

func _PingPong_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingPongReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpongapi.PingPong/PingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).PingPong(ctx, req.(*PingPongReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingPong_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pingpongapi.PingPong",
	HandlerType: (*PingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _PingPong_PingPong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pingpongapi/pingpongapi.proto",
}
